version: "3"
services:
  famcal_api:
    build: .
    container_name: family-calendar_BE
    command: node ./server.js
    restart: always
    ports:
      - "9000:9000"
    environment:
      - MONGO_URL='mongodb://mongo_db'
      - PRODUCTION=true
networks:
  default:
    external:
      name: squishychat_default
